### ISSUE TITLE
Should we use BoundingBoxInput type in goldfinch?

### ISSUE THREAD

**Issue by agstephens** [cedadev/goldfinch#1]
At present, we are using a string and converting to a box internally. Might need to use the BoundingBoxInput so that we can link it to Phoenix.

**Comment by antony-wilson** [comment]
our version of pheonix will work with BoundingBoxInput type. This has been tested with an updated version of EMU. The extent of the bbox has to be defined in the `crss` attribute
```
class Box(Process):
    def __init__(self):
        inputs = [
            BoundingBoxInput('bbox', 'Bounding Box',
                             abstract='Bounding Box Input.',
                             crss=['-170, -90, 160, 90,epsg:4326x'],
                             min_occurs=0)
        ]
```

**Comment by agstephens** [comment]
@antony-wilson can you give me an example of an input that you would expect the client to send.

What should the `bbox` value look like in the request URL?

`-10,45,1,60,epsg:4326x` or `-10,45,1,60` - or either?

**Comment by antony-wilson** [comment]
@agstephens It looks like emu is recieving a `POST` when a job is submitted from phoenix
```
127.0.0.1 - - [16/Nov/2020 13:34:44] "GET /wps?service=WPS&request=GetCapabilities&version=1.0.0 HTTP/1.1" 200 -
127.0.0.1 - - [16/Nov/2020 13:34:44] "POST /wps HTTP/1.1" 200 -
```
the emu code is https://github.com/bird-house/emu/blob/master/emu/processes/wps_bbox.py

**Comment by agstephens** [comment]
@antony-wilson @jhaigh0 @cehbrecht I have forked `pywps` to monkey patch the way that the input `BoundingBox` is parsed. The original code only works with XML inputs, whereas my version accepts a string and just uses the first 4 values as the bounding box limits (left, lower, right, upper):

https://github.com/cedadev/pywps/commit/53f5ec16b85256689e6a15a1ac1055cc382758b6

This patch is required to support the `BoundingBox` input type in our goldfinch implementation.

@cehbrecht : Thoughts?

**Comment by cehbrecht** [comment]
I'm not sure if I understand the issue. The problem is that the bbox (using `BoundingBoxInput`) can not be set on the client side (phoenix)? Or do you have troubles reading the bbox values (left, lower, right, upper) on the server side (goldfinch)?

**Comment by cehbrecht** [comment]
I'm testing it with Emu WPS. I think you have the issue that the bbox is not correctly handled in pywps ...

**Comment by agstephens** [comment]
@cehbrecht, yes - the issue is that the `pywps` library will fail if it receives a URL with a `BoundingBoxInput` that does not have attributes: `[datainput.minx, datainput.miny, datainput.maxx, datainput.maxy]`

Since we are providing a simple string input (in a URL query string) then we need something that will parse a string looking like: `x1,y1,x2,y2`

My fix in the fork does this. Do you think this is adequate? Do you know anyone who actually uses the Bounding Box Input type in their WPS?

**Comment by cehbrecht** [comment]
@agstephens I have made a patch for pywps to fix this:
https://github.com/geopython/pywps/pull/551

The `Post` request should have worked before but the `Get` request failed. In the current PR the `CRS` is not parsed from the `Get` request.

**Comment by agstephens** [comment]
@cehbrecht That looks brilliant. Let me know when it has been merged and we'll pull from master.

Thanks for sorting this out. It will really help us. 

Tagging @antony-wilson @jhaigh0

**Comment by cehbrecht** [comment]
@agstephens @antony-wilson @jhaigh0 I have merged the bbox fix:
https://github.com/geopython/pywps/pull/551

You need to use the pywps-4.2 branch (master will not work):
https://github.com/geopython/pywps/tree/pywps-4.2

Maybe we need to patch more ... but I can make a new pywps release when needed ... end of this month.

**Comment by agstephens** [comment]
We are using this. It works!
